### ISSUE TITLE
Support Alpine releases with out having to install libc6-compat

### ISSUE THREAD

**Issue by drubin** [Code0x58/gitlab-ci-validate#4]
From this stack overflow post we could support `alpine` if we.

* Disable CGO, via CGO_ENABLED=0
* Force the use of the Go implementation of net dependencies, netgo via go build -tags netgo -a -v, this is implemented for a certain platforms

https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host/36308464#36308464

Would this be something you would be willing to accept? If so which one would you prefer? I have mostly seen it done via `CGO_ENABLED=0` but I am not the most experienced go dev.

**Comment by Code0x58** [comment]
Thanks for pointing out the issue!

I just pushed https://github.com/Code0x58/gitlab-ci-validate/commit/5fd2422cfc5c9e6eca7df98905318859ae88ffbd which will hopefully sort it and be available [here](https://github.com/Code0x58/gitlab-ci-validate/releases/tag/v0.2.2) when the GitHub actions have completed.

Please let me know how it goes

**Comment by Code0x58** [comment]
There was a transient failure, but the release is now out as [v0.2.2](https://github.com/Code0x58/gitlab-ci-validate/releases/tag/v0.2.2)

**Comment by drubin** [comment]
I just tested it and it works thanks!! 

Currently using this on our internal gitlab templates repo. 

Thanks very much for publishing it.

```yaml
validate gitlab-ci:
  stage: lint
  image: alpine
  variables:
    # Talk to internal gitlab url
    GITLAB_HOST: xxxx
  before_script:
  - wget -O gitlab-ci-validate https://github.com/Code0x58/gitlab-ci-validate/releases/download/v0.2.2/gitlab-ci-validate_linux_amd6
  - echo "5ebbb1889e8102f96a32cd6a8739aa31aef2d93d  gitlab-ci-validate" | sha1sum -c -
  - chmod +x gitlab-ci-validate
  script:
  - find $(pwd) -name '*.yml' -print0 | xargs -0 ./gitlab-ci-validate
```
